version: '3.9' 

services:
  postgres:
    container_name: go-simple-rpg-api
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-simple-rpg-apidocker ps


      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:




